### ISSUE TITLE
Using Colrspace to generate colors in between two luminance/lightness levels

### ISSUE THREAD

**Issue by ericmelse** [benjann/colrspace#4]
Dear Ben,

Working further to generate colors in between two luminance/lightness levels, I am reading your documentation in the Online supplement to your _Stata Journal_ paper [Color palettes for Stata graphics: An update](https://doi.org/10.1177/1536867X231175264), from page 21.
I want to generate an achromatic range of colors (i.e. grays) in between the lowest level (0 for black) and the highest level (100 for white) in the LCh color space (radial CIE _L_* a* b* ). The code that I use is:
```
mata: S.clear() // reinitialize
mata: S.palette("LCh", 100, (0, 0), (0, 0), (0, 100)) // 100 steps ?
colorpalette, gropts(ysize(1) scale(*10) graphreg(m(t-16 b-25 l-13 r-16)) plotreg(m(l-2))) nonumbers labels(S) : mata(S)
```
which results in:
![mata_ColrSpace_LCh_100steps_achromatic_chrom0_L0t100](https://github.com/benjann/colrspace/assets/3686136/9822cb78-9229-4050-9c92-f10b277f329d)
and this is not what I expect (all gradient steps are black).
So, next I tried a similar scale example between yellow and blue with their chroma (C) set at 40 and lightness (L) at 50 using:
```
mata: S.clear() // reinitialize
mata: S.palette("LCh", 100, (90, 270), (40, 40), (50, 50)) // 100 steps
colorpalette, gropts(ysize(1) scale(*10) graphreg(m(t-16 b-25 l-13 r-16)) plotreg(m(l-2))) nonumbers labels(S) : mata(S)
```
which results in:
![mata_ColrSpace_LCh_100steps_yellow_blue_chrom40_L50t50](https://github.com/benjann/colrspace/assets/3686136/221674eb-68ce-437b-a518-0b9a42a9d1ac)
this result looks about right to me.
Next I changed the lightness (L) for the second color to 80 using:
```
mata: S.clear() // reinitialize
mata: S.palette("LCh", 100, (90, 270), (40, 40), (50, 80)) // 100 steps
colorpalette, gropts(ysize(1) scale(*10) graphreg(m(t-16 b-25 l-13 r-16)) plotreg(m(l-2))) nonumbers labels(S) : mata(S)
```
which results in:
![mata_ColrSpace_LCh_100steps_yellow_blue_chrom40_L50t80](https://github.com/benjann/colrspace/assets/3686136/314ab1be-031a-4028-ad22-972b5e504368)
this result does not look right to me as it is identical to the above result when the second color lightness (L) is set to 50.

So, could it be that the second parameter for lightness (L)  is not processed correctly?

To test this I now set the first color lightness (L) to 80 while the second color lightness (L) is set to 50 using:
```
mata: S.clear() // reinitialize
mata: S.palette("LCh", 100, (90, 270), (40, 40), (80, 50)) // 100 steps
colorpalette, gropts(ysize(1) scale(*10) graphreg(m(t-16 b-25 l-13 r-16)) plotreg(m(l-2))) nonumbers labels(S) : mata(S)
```
which results in:
![mata_ColrSpace_LCh_100steps_yellow_blue_chrom40_L80t50](https://github.com/benjann/colrspace/assets/3686136/ca3c89b4-398d-48b3-a1d1-5cc9535545f5)
this result shows that it is only the first color lightness (L) parameter that is used by `Colrspace` and this, I think, is problematic for generating both chromatic and achromatic scales.
I have not tried if this issue also occurs with other color spaces.

On a side note, about getting a 'smooth' visual impression of a gradient scale of colors, also these palettes get their steps 'ragged' at their edges (I believe you draw them as an `area`), which seems to be further evidence that it is Statas's graphic engine that causes that issue to occur.

**Comment by benjann** [comment]
Hi Eric

different formulas are used for the color generators depending on type (qualitative, sequential, or diverging); see page 23. The default type is qualitative. That is, if you just type `"LCh"`, then `"LCh qualitative"` is assumed. If you look at the formulas you will see that for this type only the hue is interpolated. I admit that the documentation is not very clear here. The description of the arguments on page 22 should mention that the interpretation depends on selected type of generator.

In your case, you would need to type

```
mata: S.palette("LCh sequential", 100, (0, 0), (0, 0), (0, 100))
```
Could also abbreviate as, e.g., `"LCh seq"`.

> On a side note, about getting a 'smooth' visual impression of a gradient scale of colors, also these palettes get their steps 'ragged' at their edges (I believe you draw them as an area), which seems to be further evidence that it is Statas's graphic engine that causes that issue to occur.

Yes, this is a rendering issue. Depending on device you can have more or less of such visual effects.
ben

**Comment by ericmelse** [comment]
Thank you Ben, for explaining how the options can be used depending on which type (scheme) is set for generating intermediate colors. This indeed renders the result that I am looking for:
![mata_ColrSpace_LCh_100steps_achromatic_chrom0_L0t100s](https://github.com/benjann/colrspace/assets/3686136/66daf011-4101-4910-8897-0b103f49fc07)
And likewise:
`mata: S.palette("LCh seq", 100, (90, 270), (40, 40), (80, 50)) // 100 steps`
which results in:
![mata_ColrSpace_LCh_100steps_yellow_blue_chrom40_L80t50s](https://github.com/benjann/colrspace/assets/3686136/aee4c4ce-2e5e-4638-8c6f-800371c070d6)

After saving the RGB codes I have continued working on the improvement of the rendered result (taking note of your comments).
